apiVersion: v1
kind: Service
metadata:
  name: wm-msr-svc
  namespace: wm-msr
  labels:
    app: wm-msr-svc
spec:
  type: NodePort
  selector:
    app: wm-msr
  ports:
  - protocol: TCP
    port: 5555
    targetPort: wm-msr-port
    